import { createElement } from 'lwc';
import ContactList from 'c/contactList';
import getContacts from '@salesforce/apex/ContactController.getContacts';

const mockContactList = require("./data/getContacts.json");

describe('c-contact-list', () => {
	afterEach(() => {
			// The jsdom instance is shared across test cases in a single file so reset the DOM
		while (document.body.firstChild) {
			document.body.removeChild(document.body.firstChild);
		}
	});

	it('TODO: test case generated by CLI command, please fill in test logic', () => {
		const contactListElements = createElement('c-contact-list', { is: ContactList });
		document.body.appendChild(contactListElements);
		getContacts.emit(mockContactList);
		return Promise.resolve().then(() => {
			const contactElements = contactListElements.shadowRoot.querySelectorAll("tbody tr.slds-hint-parent");
			for (let i = 0; i < contactElements.length; i++){
				let trElement = contactElements[i];
				let tdElements = trElement.querySelectorAll('td');
				expect(tdElements[0].textContent).toBe(mockContactList[i].Name);
				expect(tdElements[1].textContent).toBe(mockContactList[i].Title);
				expect(tdElements[2].textContent).toBe(mockContactList[i].Phone);
				expect(tdElements[3].textContent).toBe(mockContactList[i].Email);
			}
		});
	});

});